require 'pry'

require_relative '../lib/game.rb'
require_relative '../lib/board.rb'
require_relative '../lib/match.rb'
require_relative '../lib/player.rb'
require_relative '../lib/human.rb'
require_relative '../lib/cpu.rb'
require_relative '../lib/one_player.rb'
require_relative '../lib/two_player.rb'
require_relative '../lib/game.rb'
